<?php

use Illuminate\Database\Seeder;
use App\Country;
use App\Province;
use App\City;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(['id'=>'1','iso'=>'AF','country' => 'Afganistán']);
    	DB::table('countries')->insert(['id'=>'2','iso'=>'AX','country' => 'Islas Gland']);
    	DB::table('countries')->insert(['id'=>'3','iso'=>'AL','country' => 'Albania']);
    	DB::table('countries')->insert(['id'=>'4','iso'=>'DE','country' => 'Alemania']);
    	DB::table('countries')->insert(['id'=>'5','iso'=>'AD','country' => 'Andorra']);
    	DB::table('countries')->insert(['id'=>'6','iso'=>'AO','country' => 'Angola']);
    	DB::table('countries')->insert(['id'=>'7','iso'=>'AI','country' => 'Anguilla']);
    	DB::table('countries')->insert(['id'=>'8','iso'=>'AQ','country' => 'Antártida']);
    	DB::table('countries')->insert(['id'=>'9','iso'=>'AG','country' => 'Antigua y Barbuda']);
    	DB::table('countries')->insert(['id'=>'10','iso'=>'AN','country'=> 'Antillas Holandesas']);
    	DB::table('countries')->insert(['id'=>'11','iso'=>'SA','country'=> 'Arabia Saudí']);
    	DB::table('countries')->insert(['id'=>'12','iso'=>'DZ','country'=> 'Argelia']);
    	DB::table('countries')->insert(['id'=>'13','iso'=>'AR','country'=> 'Argentina']);
    	DB::table('countries')->insert(['id'=>'14','iso'=>'AM','country'=> 'Armenia']);
    	DB::table('countries')->insert(['id'=>'15','iso'=>'AW','country'=> 'Aruba']);
    	DB::table('countries')->insert(['id'=>'16','iso'=>'AU','country'=> 'Australia']);
    	DB::table('countries')->insert(['id'=>'17','iso'=>'AT','country'=> 'Austria']);
    	DB::table('countries')->insert(['id'=>'18','iso'=>'AZ','country'=> 'Azerbaiyán']);
    	DB::table('countries')->insert(['id'=>'19','iso'=>'BS','country'=> 'Bahamas']);
    	DB::table('countries')->insert(['id'=>'20','iso'=>'BH','country'=> 'Bahréin']);
    	DB::table('countries')->insert(['id'=>'21','iso'=>'BD','country'=> 'Bangladesh']);
    	DB::table('countries')->insert(['id'=>'22','iso'=>'BB','country'=> 'Barbados']);
    	DB::table('countries')->insert(['id'=>'23','iso'=>'BY','country'=> 'Bielorrusia']);
    	DB::table('countries')->insert(['id'=>'24','iso'=>'BE','country'=> 'Bélgica']);
    	DB::table('countries')->insert(['id'=>'25','iso'=>'BZ','country'=> 'Belice']);
    	DB::table('countries')->insert(['id'=>'26','iso'=>'BJ','country'=> 'Benin']);
    	DB::table('countries')->insert(['id'=>'27','iso'=>'BM','country'=> 'Bermudas']);
    	DB::table('countries')->insert(['id'=>'28','iso'=>'BT','country'=> 'Bhután']);
    	DB::table('countries')->insert(['id'=>'29','iso'=>'BO','country'=> 'Bolivia']);
    	DB::table('countries')->insert(['id'=>'30','iso'=>'BA','country'=> 'Bosnia y Herzegovina']);
    	DB::table('countries')->insert(['id'=>'31','iso'=>'BW','country'=> 'Botsuana']);
    	DB::table('countries')->insert(['id'=>'32','iso'=>'BV','country'=> 'Isla Bouvet']);
    	DB::table('countries')->insert(['id'=>'33','iso'=>'BR','country'=> 'Brasil']);
    	DB::table('countries')->insert(['id'=>'34','iso'=>'BN','country'=> 'Brunéi']);
    	DB::table('countries')->insert(['id'=>'35','iso'=>'BG','country'=> 'Bulgaria']);
    	DB::table('countries')->insert(['id'=>'36','iso'=>'BF','country'=> 'Burkina Faso']);
    	DB::table('countries')->insert(['id'=>'37','iso'=>'BI','country'=> 'Burundi']);
    	DB::table('countries')->insert(['id'=>'38','iso'=>'CV','country'=> 'Cabo Verde']);
    	DB::table('countries')->insert(['id'=>'39','iso'=>'KY','country'=> 'Islas Caimán']);
    	DB::table('countries')->insert(['id'=>'40','iso'=>'KH','country'=> 'Camboya']);
    	DB::table('countries')->insert(['id'=>'41','iso'=>'CM','country'=> 'Camerún']);
    	DB::table('countries')->insert(['id'=>'42','iso'=>'CA','country'=> 'Canadá']);
    	DB::table('countries')->insert(['id'=>'43','iso'=>'CF','country'=> 'República-Centroafricana']);
    	DB::table('countries')->insert(['id'=>'44','iso'=>'TD','country'=> 'Chad']);
    	DB::table('countries')->insert(['id'=>'45','iso'=>'CZ','country'=> 'República Checa']);
    	DB::table('countries')->insert(['id'=>'46','iso'=>'CL','country'=> 'Chile']);
    	DB::table('countries')->insert(['id'=>'47','iso'=>'CN','country'=> 'China']);
    	DB::table('countries')->insert(['id'=>'48','iso'=>'CY','country'=> 'Chipre']);
    	DB::table('countries')->insert(['id'=>'49','iso'=>'CX','country'=> 'Isla de Navidad']);
    	DB::table('countries')->insert(['id'=>'50','iso'=>'VA','country'=> 'Ciudad del Vaticano']);
    	DB::table('countries')->insert(['id'=>'51','iso'=>'CC','country'=> 'Islas Cocos']);
    	DB::table('countries')->insert(['id'=>'52','iso'=>'CO','country'=> 'Colombia']);
    	DB::table('countries')->insert(['id'=>'53','iso'=>'KM','country'=> 'Comoras']);
    	DB::table('countries')->insert(['id'=>'54','iso'=>'CD','country'=> 'República-Democrática del Congo']);
    	DB::table('countries')->insert(['id'=>'55','iso'=>'CG','country'=> 'Congo']);
    	DB::table('countries')->insert(['id'=>'56','iso'=>'CK','country'=> 'Islas Cook']);
    	DB::table('countries')->insert(['id'=>'57','iso'=>'KP','country'=> 'Corea del Norte']);
    	DB::table('countries')->insert(['id'=>'58','iso'=>'KR','country'=> 'Corea del Sur']);
    	DB::table('countries')->insert(['id'=>'59','iso'=>'CI','country'=> 'Costa de Marfil']);
    	DB::table('countries')->insert(['id'=>'60','iso'=>'CR','country'=> 'Costa Rica']);
    	DB::table('countries')->insert(['id'=>'61','iso'=>'HR','country'=> 'Croacia']);
    	DB::table('countries')->insert(['id'=>'62','iso'=>'CU','country'=> 'Cuba']);
    	DB::table('countries')->insert(['id'=>'63','iso'=>'DK','country'=> 'Dinamarca']);
    	DB::table('countries')->insert(['id'=>'64','iso'=>'DM','country'=> 'Dominica']);
    	DB::table('countries')->insert(['id'=>'65','iso'=>'DO','country'=> 'República Dominicana']);
    	DB::table('countries')->insert(['id'=>'66','iso'=>'EC','country'=> 'Ecuador']);
    	DB::table('countries')->insert(['id'=>'67','iso'=>'EG','country'=> 'Egipto']);
    	DB::table('countries')->insert(['id'=>'68','iso'=>'SV','country'=> 'El Salvador']);
    	DB::table('countries')->insert(['id'=>'69','iso'=>'AE','country'=> 'Emiratos Árabes Unidos']);
    	DB::table('countries')->insert(['id'=>'70','iso'=>'ER','country'=> 'Eritrea']);
    	DB::table('countries')->insert(['id'=>'71','iso'=>'SK','country'=> 'Eslovaquia']);
    	DB::table('countries')->insert(['id'=>'72','iso'=>'SI','country'=> 'Eslovenia']);
    	DB::table('countries')->insert(['id'=>'73','iso'=>'ES','country'=> 'España']);
    	DB::table('countries')->insert(['id'=>'74','iso'=>'UM','country'=> 'Islas ultramarinas de Estados Unidos']);
    	DB::table('countries')->insert(['id'=>'75','iso'=>'US','country'=> 'Estados Unidos']);
    	DB::table('countries')->insert(['id'=>'76','iso'=>'EE','country'=> 'Estonia']);
    	DB::table('countries')->insert(['id'=>'77','iso'=>'ET','country'=> 'Etiopía']);
    	DB::table('countries')->insert(['id'=>'78','iso'=>'FO','country'=> 'Islas Feroe']);
    	DB::table('countries')->insert(['id'=>'79','iso'=>'PH','country'=> 'Filipinas']);
    	DB::table('countries')->insert(['id'=>'80','iso'=>'FI','country'=> 'Finlandia']);
    	DB::table('countries')->insert(['id'=>'81','iso'=> 'FJ','country'=> 'Fiyi']);
    	DB::table('countries')->insert(['id'=>'82','iso'=> 'FR','country'=> 'Francia']);
    	DB::table('countries')->insert(['id'=>'83','iso'=> 'GA','country'=> 'Gabón']);
    	DB::table('countries')->insert(['id'=>'84','iso'=> 'GM','country'=> 'Gambia']);
    	DB::table('countries')->insert(['id'=>'85','iso'=> 'GE','country'=> 'Georgia']);
    	DB::table('countries')->insert(['id'=>'86','iso'=> 'GS','country'=> 'Islas Georgias del Sur y Sandwich del Sur']);
    	DB::table('countries')->insert(['id'=>'87','iso'=> 'GH','country'=> 'Ghana']);
    	DB::table('countries')->insert(['id'=>'88','iso'=> 'GI','country'=> 'Gibraltar']);
    	DB::table('countries')->insert(['id'=>'89','iso'=> 'GD','country'=> 'Granada']);
    	DB::table('countries')->insert(['id'=>'90','iso'=> 'GR','country'=> 'Grecia']);
    	DB::table('countries')->insert(['id'=>'91','iso'=> 'GL','country'=> 'Groenlandia']);
    	DB::table('countries')->insert(['id'=>'92','iso'=> 'GP','country'=> 'Guadalupe']);
    	DB::table('countries')->insert(['id'=>'93','iso'=> 'GU','country'=> 'Guam']);
    	DB::table('countries')->insert(['id'=>'94','iso'=> 'GT','country'=> 'Guatemala']);
    	DB::table('countries')->insert(['id'=>'95','iso'=> 'GF','country'=> 'Guayana Francesa']);
    	DB::table('countries')->insert(['id'=>'96','iso'=> 'GN','country'=> 'Guinea']);
    	DB::table('countries')->insert(['id'=>'97','iso'=> 'GQ','country'=> 'Guinea Ecuatorial']);
    	DB::table('countries')->insert(['id'=>'98','iso'=> 'GW','country'=> 'Guinea-Bissau']);
    	DB::table('countries')->insert(['id'=>'99','iso'=> 'GY','country'=> 'Guyana']);
    	DB::table('countries')->insert(['id'=>'100','iso'=> 'HT','country'=> 'Haití']);
    	DB::table('countries')->insert(['id'=>'101','iso'=> 'HM','country'=> 'Islas Heard y McDonald']);
    	DB::table('countries')->insert(['id'=>'102','iso'=> 'HN','country'=> 'Honduras']);
    	DB::table('countries')->insert(['id'=>'103','iso'=> 'HK','country'=> 'Hong Kong']);
    	DB::table('countries')->insert(['id'=>'104','iso'=> 'HU','country'=> 'Hungría']);
    	DB::table('countries')->insert(['id'=>'105','iso'=> 'IN','country'=> 'India']);
    	DB::table('countries')->insert(['id'=>'106','iso'=> 'ID','country'=> 'Indonesia']);
    	DB::table('countries')->insert(['id'=>'107','iso'=> 'IR','country'=> 'Irán']);
    	DB::table('countries')->insert(['id'=>'108','iso'=> 'IQ','country'=> 'Iraq']);
    	DB::table('countries')->insert(['id'=>'109','iso'=> 'IE','country'=> 'Irlanda']);
    	DB::table('countries')->insert(['id'=>'110','iso'=> 'IS','country'=> 'Islandia']);
    	DB::table('countries')->insert(['id'=>'111','iso'=> 'IL','country'=> 'Israel']);
    	DB::table('countries')->insert(['id'=>'112','iso'=> 'IT','country'=> 'Italia']);
    	DB::table('countries')->insert(['id'=>'113','iso'=> 'JM','country'=> 'Jamaica']);
    	DB::table('countries')->insert(['id'=>'114','iso'=> 'JP','country'=> 'Japón']);
    	DB::table('countries')->insert(['id'=>'115','iso'=> 'JO','country'=> 'Jordania']);
    	DB::table('countries')->insert(['id'=>'116','iso'=> 'KZ','country'=> 'Kazajstán']);
    	DB::table('countries')->insert(['id'=>'117','iso'=> 'KE','country'=> 'Kenia']);
    	DB::table('countries')->insert(['id'=>'118','iso'=> 'KG','country'=> 'Kirguistán']);
    	DB::table('countries')->insert(['id'=>'119','iso'=> 'KI','country'=> 'Kiribati']);
    	DB::table('countries')->insert(['id'=>'120','iso'=> 'KW','country'=> 'Kuwait']);
    	DB::table('countries')->insert(['id'=>'121','iso'=> 'LA','country'=> 'Laos']);
    	DB::table('countries')->insert(['id'=>'122','iso'=> 'LS','country'=> 'Lesotho']);
    	DB::table('countries')->insert(['id'=>'123','iso'=> 'LV','country'=> 'Letonia']);
    	DB::table('countries')->insert(['id'=>'124','iso'=> 'LB','country'=> 'Líbano']);
    	DB::table('countries')->insert(['id'=>'125','iso'=> 'LR','country'=> 'Liberia']);
    	DB::table('countries')->insert(['id'=>'126','iso'=> 'LY','country'=> 'Libia']);
    	DB::table('countries')->insert(['id'=>'127','iso'=> 'LI','country'=> 'Liechtenstein']);
    	DB::table('countries')->insert(['id'=>'128','iso'=> 'LT','country'=> 'Lituania']);
    	DB::table('countries')->insert(['id'=>'129','iso'=> 'LU','country'=> 'Luxemburgo']);
    	DB::table('countries')->insert(['id'=>'130','iso'=> 'MO','country'=> 'Macao']);
    	DB::table('countries')->insert(['id'=>'131','iso'=> 'MK','country'=> 'ARY Macedonia']);
    	DB::table('countries')->insert(['id'=>'132','iso'=> 'MG','country'=> 'Madagascar']);
    	DB::table('countries')->insert(['id'=>'133','iso'=> 'MY','country'=> 'Malasia']);
    	DB::table('countries')->insert(['id'=>'134','iso'=> 'MW','country'=> 'Malawi']);
    	DB::table('countries')->insert(['id'=>'135','iso'=> 'MV','country'=> 'Maldivas']);
    	DB::table('countries')->insert(['id'=>'136','iso'=> 'ML','country'=> 'Malí']);
    	DB::table('countries')->insert(['id'=>'137','iso'=> 'MT','country'=> 'Malta']);
    	DB::table('countries')->insert(['id'=>'138','iso'=> 'FK','country'=> 'Islas Malvinas']);
    	DB::table('countries')->insert(['id'=>'139','iso'=> 'MP','country'=> 'Islas Marianas del Norte']);
    	DB::table('countries')->insert(['id'=>'140','iso'=> 'MA','country'=> 'Marruecos']);
    	DB::table('countries')->insert(['id'=>'141','iso'=> 'MH','country'=> 'Islas Marshall']);
    	DB::table('countries')->insert(['id'=>'142','iso'=> 'MQ','country'=> 'Martinica']);
    	DB::table('countries')->insert(['id'=>'143','iso'=> 'MU','country'=> 'Mauricio']);
    	DB::table('countries')->insert(['id'=>'144','iso'=> 'MR','country'=> 'Mauritania']);
    	DB::table('countries')->insert(['id'=>'145','iso'=> 'YT','country'=> 'Mayotte']);
    	DB::table('countries')->insert(['id'=>'146','iso'=> 'MX','country'=> 'México']);
    	DB::table('countries')->insert(['id'=>'147','iso'=> 'FM','country'=> 'Micronesia']);
    	DB::table('countries')->insert(['id'=>'148','iso'=> 'MD','country'=> 'Moldavia']);
    	DB::table('countries')->insert(['id'=>'149','iso'=> 'MC','country'=> 'Mónaco']);
    	DB::table('countries')->insert(['id'=>'150','iso'=> 'MN','country'=> 'Mongolia']);
    	DB::table('countries')->insert(['id'=>'151','iso'=> 'MS','country'=> 'Montserrat']);
    	DB::table('countries')->insert(['id'=>'152','iso'=> 'MZ','country'=> 'Mozambique']);
    	DB::table('countries')->insert(['id'=>'153','iso'=> 'MM','country'=> 'Myanmar']);
    	DB::table('countries')->insert(['id'=>'154','iso'=> 'NA','country'=> 'Namibia']);
    	DB::table('countries')->insert(['id'=>'155','iso'=> 'NR','country'=> 'Nauru']);
    	DB::table('countries')->insert(['id'=>'156','iso'=> 'NP','country'=> 'Nepal']);
    	DB::table('countries')->insert(['id'=>'157','iso'=> 'NI','country'=> 'Nicaragua']);
    	DB::table('countries')->insert(['id'=>'158','iso'=> 'NE','country'=> 'Níger']);
    	DB::table('countries')->insert(['id'=>'159','iso'=> 'NG','country'=> 'Nigeria']);
    	DB::table('countries')->insert(['id'=>'160','iso'=> 'NU','country'=> 'Niue']);
    	DB::table('countries')->insert(['id'=>'161','iso'=> 'NF','country'=> 'Isla Norfolk']);
    	DB::table('countries')->insert(['id'=>'162','iso'=> 'NO','country'=> 'Noruega']);
    	DB::table('countries')->insert(['id'=>'163','iso'=> 'NC','country'=> 'Nueva Caledonia']);
    	DB::table('countries')->insert(['id'=>'164','iso'=> 'NZ','country'=> 'Nueva Zelanda']);
    	DB::table('countries')->insert(['id'=>'165','iso'=> 'OM','country'=> 'Omán']);
    	DB::table('countries')->insert(['id'=>'166','iso'=> 'NL','country'=> 'Países Bajos']);
    	DB::table('countries')->insert(['id'=>'167','iso'=> 'PK','country'=> 'Pakistán']);
    	DB::table('countries')->insert(['id'=>'168','iso'=> 'PW','country'=> 'Palau']);
    	DB::table('countries')->insert(['id'=>'169','iso'=> 'PS','country'=> 'Palestina']);
    	DB::table('countries')->insert(['id'=>'170','iso'=> 'PA','country'=> 'Panamá']);
    	DB::table('countries')->insert(['id'=>'171','iso'=> 'PG','country'=> 'Papúa Nueva Guinea']);
    	DB::table('countries')->insert(['id'=>'172','iso'=> 'PY','country'=> 'Paraguay']);
    	DB::table('countries')->insert(['id'=>'173','iso'=> 'PE','country'=> 'Perú']);
    	DB::table('countries')->insert(['id'=>'174','iso'=> 'PN','country'=> 'Islas Pitcairn']);
    	DB::table('countries')->insert(['id'=>'175','iso'=> 'PF','country'=> 'Polinesia Francesa']);
    	DB::table('countries')->insert(['id'=>'176','iso'=> 'PL','country'=> 'Polonia']);
    	DB::table('countries')->insert(['id'=>'177','iso'=> 'PT','country'=> 'Portugal']);
    	DB::table('countries')->insert(['id'=>'178','iso'=> 'PR','country'=> 'Puerto Rico']);
    	DB::table('countries')->insert(['id'=>'179','iso'=> 'QA','country'=> 'Qatar']);
    	DB::table('countries')->insert(['id'=>'180','iso'=> 'GB','country'=> 'Reino Unido']);
    	DB::table('countries')->insert(['id'=>'181','iso'=> 'RE','country'=> 'Reunión']);
    	DB::table('countries')->insert(['id'=>'182','iso'=> 'RW','country'=> 'Ruanda']);
    	DB::table('countries')->insert(['id'=>'183','iso'=> 'RO','country'=> 'Rumania']);
    	DB::table('countries')->insert(['id'=>'184','iso'=> 'RU','country'=> 'Rusia']);
    	DB::table('countries')->insert(['id'=>'185','iso'=> 'EH','country'=> 'Sahara Occidental']);
    	DB::table('countries')->insert(['id'=>'186','iso'=> 'SB','country'=> 'Islas Salomón']);
    	DB::table('countries')->insert(['id'=>'187','iso'=> 'WS','country'=> 'Samoa']);
    	DB::table('countries')->insert(['id'=>'188','iso'=> 'AS','country'=> 'Samoa Americana']);
    	DB::table('countries')->insert(['id'=>'189','iso'=> 'KN','country'=> 'San Cristóbal y Nevis']);
    	DB::table('countries')->insert(['id'=>'190','iso'=> 'SM','country'=> 'San Marino']);
    	DB::table('countries')->insert(['id'=>'191','iso'=> 'PM','country'=> 'San Pedro y Miquelón']);
    	DB::table('countries')->insert(['id'=>'192','iso'=> 'VC','country'=> 'San Vicente y las Granadinas']);
    	DB::table('countries')->insert(['id'=>'193','iso'=> 'SH','country'=> 'Santa Helena']);
    	DB::table('countries')->insert(['id'=>'194','iso'=> 'LC','country'=> 'Santa Lucía']);
    	DB::table('countries')->insert(['id'=>'195','iso'=> 'ST','country'=> 'Santo Tomé y Príncipe']);
    	DB::table('countries')->insert(['id'=>'196','iso'=> 'SN','country'=> 'Senegal']);
    	DB::table('countries')->insert(['id'=>'197','iso'=> 'CS','country'=> 'Serbia y Montenegro']);
    	DB::table('countries')->insert(['id'=>'198','iso'=> 'SC','country'=> 'Seychelles']);
    	DB::table('countries')->insert(['id'=>'199','iso'=> 'SL','country'=> 'Sierra Leona']);
    	DB::table('countries')->insert(['id'=>'200','iso'=> 'SG','country'=> 'Singapur']);
    	DB::table('countries')->insert(['id'=>'201','iso'=> 'SY','country'=> 'Siria']);
    	DB::table('countries')->insert(['id'=>'202','iso'=> 'SO','country'=> 'Somalia']);
    	DB::table('countries')->insert(['id'=>'203','iso'=> 'LK','country'=> 'Sri Lanka']);
    	DB::table('countries')->insert(['id'=>'204','iso'=> 'SZ','country'=> 'Suazilandia']);
    	DB::table('countries')->insert(['id'=>'205','iso'=> 'ZA','country'=> 'Sudáfrica']);
    	DB::table('countries')->insert(['id'=>'206','iso'=> 'SD','country'=> 'Sudán']);
    	DB::table('countries')->insert(['id'=>'207','iso'=> 'SE','country'=> 'Suecia']);
    	DB::table('countries')->insert(['id'=>'208','iso'=> 'CH','country'=> 'Suiza']);
    	DB::table('countries')->insert(['id'=>'209','iso'=> 'SR','country'=> 'Surinam']);
    	DB::table('countries')->insert(['id'=>'210','iso'=> 'SJ','country'=> 'Svalbard y Jan Mayen']);
    	DB::table('countries')->insert(['id'=>'211','iso'=> 'TH','country'=> 'Tailandia']);
    	DB::table('countries')->insert(['id'=>'212','iso'=> 'TW','country'=> 'Taiwán']);
    	DB::table('countries')->insert(['id'=>'213','iso'=> 'TZ','country'=> 'Tanzania']);
    	DB::table('countries')->insert(['id'=>'214','iso'=> 'TJ','country'=> 'Tayikistán']);
    	DB::table('countries')->insert(['id'=>'215','iso'=> 'IO','country'=> 'Territorio Británico del Océano Índico']);
    	DB::table('countries')->insert(['id'=>'216','iso'=> 'TF','country'=> 'Territorios Australes Franceses']);
    	DB::table('countries')->insert(['id'=>'217','iso'=> 'TL','country'=> 'Timor Oriental']);
    	DB::table('countries')->insert(['id'=>'218','iso'=> 'TG','country'=> 'Togo']);
    	DB::table('countries')->insert(['id'=>'219','iso'=> 'TK','country'=> 'Tokelau']);
    	DB::table('countries')->insert(['id'=>'220','iso'=> 'TO','country'=> 'Tonga']);
    	DB::table('countries')->insert(['id'=>'221','iso'=> 'TT','country'=> 'Trinidad y Tobago']);
    	DB::table('countries')->insert(['id'=>'222','iso'=> 'TN','country'=> 'Túnez']);
    	DB::table('countries')->insert(['id'=>'223','iso'=> 'TC','country'=> 'Islas Turcas y Caicos']);
    	DB::table('countries')->insert(['id'=>'224','iso'=> 'TM','country'=> 'Turkmenistán']);
    	DB::table('countries')->insert(['id'=>'225','iso'=> 'TR','country'=> 'Turquía']);
    	DB::table('countries')->insert(['id'=>'226','iso'=> 'TV','country'=> 'Tuvalu']);
    	DB::table('countries')->insert(['id'=>'227','iso'=> 'UA','country'=> 'Ucrania']);
    	DB::table('countries')->insert(['id'=>'228','iso'=> 'UG','country'=> 'Uganda']);
    	DB::table('countries')->insert(['id'=>'229','iso'=> 'UY','country'=> 'Uruguay']);
    	DB::table('countries')->insert(['id'=>'230','iso'=> 'UZ','country'=> 'Uzbekistán']);
    	DB::table('countries')->insert(['id'=>'231','iso'=> 'VU','country'=> 'Vanuatu']);
    	DB::table('countries')->insert(['id'=>'232','iso'=> 'VE','country'=> 'Venezuela']);
    	DB::table('countries')->insert(['id'=>'233','iso'=> 'VN','country'=> 'Vietnam']);
    	DB::table('countries')->insert(['id'=>'234','iso'=> 'VG','country'=> 'Islas Vírgenes Británicas']);
    	DB::table('countries')->insert(['id'=>'235','iso'=> 'VI','country'=> 'Isla Vírgene Estados Unidos']);
    	DB::table('countries')->insert(['id'=>'236','iso'=> 'WF','country'=> 'Wallis y Futuna']);
    	DB::table('countries')->insert(['id'=>'237','iso'=> 'YE','country'=> 'Yemen']);
    	DB::table('countries')->insert(['id'=>'238','iso'=> 'DJ','country'=> 'Yibuti']);
    	DB::table('countries')->insert(['id'=>'239','iso'=> 'ZM','country'=> 'Zambia']);
        DB::table('countries')->insert(['id'=>'240','iso'=> 'ZW','country'=> 'Zimbabue']);
        DB::table('provinces')->insert(['province'=> 'AZUAY','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'BOLIVAR','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'CAÑAR','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'CARCHI','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'COTOPAXI','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'CHIMBORAZO','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'EL ORO','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'ESMERALDAS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'GUAYAS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'IMBABURA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'LOJA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'LOS RIOS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'MANABI','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'MORONA SANTIAGO','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'NAPO','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'PASTAZA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'PICHINCHA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'TUNGURAHUA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'ZAMORA CHINCHIPE','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'GALAPAGOS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'SUCUMBIOS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'ORELLANA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'SANTO DOMINGO DE LOS TSACHILAS','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'SANTA ELENA','id_country'=>'66']);
        DB::table('provinces')->insert(['province'=> 'ZONAS NO DELIMITADAS','id_country'=>'66']);
        
        

    }
}
